SET DATABASE SQL SYNTAX PGS TRUE;

CREATE TABLE IF NOT EXISTS users(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(50) UNIQUE NOT NULL,
    forename VARCHAR(50) NOT NULL,
    surname VARCHAR(50) NOT NULL,
    password_hash VARCHAR(255),
    email_validated BOOLEAN,
    phone_number VARCHAR(20),
    birth_date DATE,
    about VARCHAR(500),
    profile_picture_id BIGINT,
    latest_locale VARCHAR(32),
    cbu VARCHAR(22),
    license_file_id BIGINT,
    license_validated BOOLEAN NOT NULL DEFAULT FALSE,
    identity_file_id BIGINT,
    identity_validated BOOLEAN NOT NULL DEFAULT FALSE,
    member_since DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS cars (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    owner_id BIGINT NOT NULL,
    plate VARCHAR(50) NOT NULL,
    brand VARCHAR(50) NOT NULL,
    model VARCHAR(50) NOT NULL,
    type VARCHAR(50) NOT NULL,
    transmission VARCHAR(50) NOT NULL,
    powertrain VARCHAR(50) NOT NULL,

    FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS neighborhoods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(160) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS listings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(105) NOT NULL,
    car_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('active', 'paused', 'finished')),
    day_price DECIMAL(10, 2) NOT NULL,
    start_point_street VARCHAR(50) NOT NULL,
    start_point_number VARCHAR(10) NOT NULL DEFAULT '',
    description VARCHAR(200) NOT NULL,
    check_in_time TIME NOT NULL,
    check_out_time TIME NOT NULL,
    neighborhood_id BIGINT,
    rating_avg DECIMAL(4, 2),

    FOREIGN KEY (car_id) REFERENCES cars(id) ON DELETE CASCADE,
    FOREIGN KEY (neighborhood_id) REFERENCES neighborhoods(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS listing_availability(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id BIGINT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL CHECK (end_date >= start_date),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,

    FOREIGN KEY (listing_id) REFERENCES listings(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS stored_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uploader_user_id BIGINT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    byte_array VARBINARY(20971520) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    FOREIGN KEY (uploader_user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rider_id BIGINT NOT NULL,
    listing_id BIGINT NOT NULL,
    start_date TIMESTAMP WITH TIME ZONE NOT NULL,
    end_date TIMESTAMP WITH TIME ZONE NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('pending', 'accepted', 'started', 'cancelled', 'finished')),
    total_price DECIMAL(10, 2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    payment_receipt_file_id BIGINT,
    payment_approved BOOLEAN NOT NULL DEFAULT FALSE,
    payment_proof_deadline_at TIMESTAMP WITH TIME ZONE,
    car_returned BOOLEAN NOT NULL DEFAULT FALSE,
    return_reminder_email_sent BOOLEAN NOT NULL DEFAULT FALSE,
    return_checkout_email_sent BOOLEAN NOT NULL DEFAULT FALSE,
    rider_review_invite_email_sent BOOLEAN NOT NULL DEFAULT FALSE,

    FOREIGN KEY (rider_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (listing_id) REFERENCES listings(id) ON DELETE CASCADE,
    FOREIGN KEY (payment_receipt_file_id) REFERENCES stored_files(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS reviews (
    reservation_id BIGINT NOT NULL,
    made_by_rider BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    rating INTEGER NOT NULL,
    comment VARCHAR(500),
    PRIMARY KEY (reservation_id, made_by_rider),
    FOREIGN KEY (reservation_id) REFERENCES reservations(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(50) NOT NULL,
    byte_array VARBINARY(20971520) NOT NULL
);

CREATE TABLE IF NOT EXISTS car_pictures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    car_id BIGINT NOT NULL,
    image_id BIGINT NOT NULL,
    display_order INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,

    UNIQUE (car_id, display_order),
    FOREIGN KEY (car_id) REFERENCES cars(id) ON DELETE CASCADE,
    FOREIGN KEY (image_id) REFERENCES images(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS email_verification_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    code VARCHAR(6) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS password_reset_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    code VARCHAR(6) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user_roles (
    user_id BIGINT NOT NULL,
    role VARCHAR(50) NOT NULL,
    PRIMARY KEY (user_id, role),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

INSERT INTO neighborhoods (id, name) VALUES
    (1, 'Agronomía'), (2, 'Almagro'), (3, 'Balvanera'), (4, 'Barracas'), (5, 'Belgrano'), (6, 'Boedo'),
    (7, 'Caballito'), (8, 'Chacarita'), (9, 'Coghlan'), (10, 'Colegiales'), (11, 'Constitución'),
    (12, 'Flores'), (13, 'Floresta'), (14, 'La Boca'), (15, 'La Paternal'), (16, 'Liniers'),
    (17, 'Mataderos'), (18, 'Monte Castro'), (19, 'Montserrat'), (20, 'Nueva Pompeya'), (21, 'Núñez'),
    (22, 'Palermo'), (23, 'Parque Avellaneda'), (24, 'Parque Chacabuco'), (25, 'Parque Chas'),
    (26, 'Parque Patricios'), (27, 'Puerto Madero'), (28, 'Recoleta'), (29, 'Retiro'), (30, 'Saavedra'),
    (31, 'San Cristóbal'), (32, 'San Nicolás'), (33, 'San Telmo'), (34, 'Vélez Sarsfield'), (35, 'Versalles'),
    (36, 'Villa Crespo'), (37, 'Villa del Parque'), (38, 'Villa Devoto'), (39, 'Villa General Mitre'),
    (40, 'Villa Lugano'), (41, 'Villa Luro'), (42, 'Villa Ortúzar'), (43, 'Villa Pueyrredón'),
    (44, 'Villa Real'), (45, 'Villa Riachuelo'), (46, 'Villa Santa Rita'), (47, 'Villa Soldati'),
    (48, 'Villa Urquiza');

ALTER TABLE users ADD CONSTRAINT fk_users_license_file_id FOREIGN KEY (license_file_id) REFERENCES stored_files(id) ON DELETE SET NULL;
ALTER TABLE users ADD CONSTRAINT fk_users_identity_file_id FOREIGN KEY (identity_file_id) REFERENCES stored_files(id) ON DELETE SET NULL;

