SET DATABASE SQL SYNTAX PGS TRUE;

CREATE SEQUENCE users_id_seq AS BIGINT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE cars_id_seq AS BIGINT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE neighborhoods_id_seq AS BIGINT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE listing_availability_id_seq AS BIGINT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE stored_files_id_seq AS BIGINT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE reservations_id_seq AS BIGINT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE images_id_seq AS BIGINT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE car_pictures_id_seq AS BIGINT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE reservation_messages_id_seq AS BIGINT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE car_brands_id_seq AS BIGINT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE car_models_id_seq AS BIGINT START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS users(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(50) UNIQUE NOT NULL,
    forename VARCHAR(50) NOT NULL,
    surname VARCHAR(50) NOT NULL,
    password_hash VARCHAR(255),
    email_validated BOOLEAN,
    phone_number VARCHAR(20),
    birth_date DATE,
    about VARCHAR(500),
    profile_picture_id BIGINT,
    latest_locale VARCHAR(32),
    cbu VARCHAR(22),
    license_file_id BIGINT,
    license_validated BOOLEAN NOT NULL DEFAULT FALSE,
    identity_file_id BIGINT,
    identity_validated BOOLEAN NOT NULL DEFAULT FALSE,
    member_since DATE NOT NULL,
    rating_as_rider NUMERIC(4, 2),
    rating_as_owner NUMERIC(4, 2),
    user_role VARCHAR(50) NOT NULL DEFAULT 'USER',
    role_assigned_by BIGINT,
    blocked BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS cars (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    owner_id BIGINT NOT NULL,
    plate VARCHAR(50) NOT NULL,
    transmission VARCHAR(50) NOT NULL,
    powertrain VARCHAR(50) NOT NULL,
    status VARCHAR(40) DEFAULT 'active' NOT NULL,
    description VARCHAR(200),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    rating_avg DECIMAL(4, 2),
    model_id BIGINT,
    insurance_file_id BIGINT,
    manufacture_year INTEGER,

    minimum_rental_days INTEGER DEFAULT 1 NOT NULL,

    CONSTRAINT cars_status_check CHECK (status IN ('active', 'paused', 'admin_paused', 'lack_doc', 'unavailable', 'deactivated')),
    CONSTRAINT cars_manufacture_year_check CHECK (manufacture_year IS NULL OR manufacture_year >= 1886),
    CONSTRAINT cars_minimum_rental_days_positive CHECK (minimum_rental_days >= 1),
    FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS neighborhoods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(160) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS car_brands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    validated BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS car_models (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id BIGINT NOT NULL,
    name VARCHAR(50) NOT NULL,
    validated BOOLEAN NOT NULL DEFAULT FALSE,
    type VARCHAR(50) NOT NULL CHECK (type IN ('SEDAN', 'HATCHBACK', 'SUV', 'COUPE', 'CONVERTIBLE', 'WAGON', 'VAN', 'PICKUP')),
    FOREIGN KEY (brand_id) REFERENCES car_brands(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS listing_availability(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    car_id BIGINT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL CHECK (end_date >= start_date),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    day_price DECIMAL(10, 2) NOT NULL,
    start_point_street VARCHAR(50) NOT NULL,
    start_point_number VARCHAR(10),
    neighborhood_id BIGINT,
    check_in_time TIME NOT NULL,
    check_out_time TIME NOT NULL,
    kind VARCHAR(20) DEFAULT 'offered' NOT NULL,

    CONSTRAINT listing_availability_kind_check CHECK (kind IN ('offered', 'withdrawn')),
    FOREIGN KEY (car_id) REFERENCES cars(id),
    FOREIGN KEY (neighborhood_id) REFERENCES neighborhoods(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS stored_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uploader_user_id BIGINT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    byte_array VARBINARY(20971520) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    FOREIGN KEY (uploader_user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rider_id BIGINT NOT NULL,
    car_id BIGINT NOT NULL,
    start_date TIMESTAMP NOT NULL,
    end_date TIMESTAMP NOT NULL,
    status VARCHAR(60) NOT NULL CHECK (status IN ('pending', 'accepted', 'started', 'cancelled', 'cancelled_by_rider', 'cancelled_by_owner', 'cancelled_due_to_missing_payment_proof', 'finished')),
    total_price DECIMAL(10, 2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    payment_receipt_file_id BIGINT,
    payment_proof_deadline_at TIMESTAMP,
    car_returned BOOLEAN NOT NULL DEFAULT FALSE,
    return_reminder_email_sent BOOLEAN NOT NULL DEFAULT FALSE,
    return_checkout_email_sent BOOLEAN NOT NULL DEFAULT FALSE,
    rider_review_invite_email_sent BOOLEAN NOT NULL DEFAULT FALSE,
    pending_paymentproof_email_sent BOOLEAN NOT NULL DEFAULT FALSE,
    payment_refund_required BOOLEAN NOT NULL DEFAULT FALSE,
    payment_refund_receipt_file_id BIGINT,
    pending_refund_email_sent BOOLEAN NOT NULL DEFAULT FALSE,
    refund_proof_deadline_at TIMESTAMP WITH TIME ZONE,
    payment_refund_approved BOOLEAN NOT NULL DEFAULT FALSE,

    FOREIGN KEY (rider_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (car_id) REFERENCES cars(id),
    FOREIGN KEY (payment_receipt_file_id) REFERENCES stored_files(id) ON DELETE SET NULL,
    FOREIGN KEY (payment_refund_receipt_file_id) REFERENCES stored_files(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS reservations_availabilities (
    reservation_id BIGINT NOT NULL,
    availability_id BIGINT NOT NULL,
    PRIMARY KEY (reservation_id, availability_id),
    FOREIGN KEY (reservation_id) REFERENCES reservations(id) ON DELETE CASCADE,
    FOREIGN KEY (availability_id) REFERENCES listing_availability(id)
);

CREATE TABLE IF NOT EXISTS reviews (
    reservation_id BIGINT NOT NULL,
    made_by_rider BOOLEAN NOT NULL,
    car_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    rating INTEGER,
    comment VARCHAR(500),
    PRIMARY KEY (reservation_id, made_by_rider),
    FOREIGN KEY (reservation_id) REFERENCES reservations(id) ON DELETE CASCADE,
    FOREIGN KEY (car_id) REFERENCES cars(id),
    CONSTRAINT reviews_rating_check CHECK (rating IS NULL OR (rating >= 1 AND rating <= 5))
);

CREATE TABLE IF NOT EXISTS reservation_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id BIGINT NOT NULL,
    sender_user_id BIGINT NOT NULL,
    body VARCHAR(1000) NOT NULL,
    attachment_file_id BIGINT NULL,
    created_at TIMESTAMP NOT NULL,
    email_notified BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (reservation_id) REFERENCES reservations(id) ON DELETE CASCADE,
    FOREIGN KEY (sender_user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (attachment_file_id) REFERENCES stored_files(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(50) NOT NULL,
    byte_array VARBINARY(20971520) NOT NULL
);

CREATE TABLE IF NOT EXISTS car_pictures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    car_id BIGINT NOT NULL,
    image_id BIGINT NULL,
    stored_file_id BIGINT NULL,
    display_order INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,

    UNIQUE (car_id, display_order),
    FOREIGN KEY (car_id) REFERENCES cars(id) ON DELETE CASCADE,
    FOREIGN KEY (image_id) REFERENCES images(id) ON DELETE CASCADE,
    FOREIGN KEY (stored_file_id) REFERENCES stored_files(id) ON DELETE CASCADE,
    CHECK (image_id IS NOT NULL OR stored_file_id IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS email_verification_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    code VARCHAR(6) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS password_reset_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    code VARCHAR(6) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

ALTER TABLE users ADD CONSTRAINT fk_users_license_file_id FOREIGN KEY (license_file_id) REFERENCES stored_files(id) ON DELETE SET NULL;
ALTER TABLE users ADD CONSTRAINT fk_users_identity_file_id FOREIGN KEY (identity_file_id) REFERENCES stored_files(id) ON DELETE SET NULL;
ALTER TABLE cars ADD CONSTRAINT fk_cars_insurance_file_id FOREIGN KEY (insurance_file_id) REFERENCES stored_files(id) ON DELETE SET NULL;

