INSERT INTO neighborhoods (id, name) VALUES (1,  'Agronomía');
INSERT INTO neighborhoods (id, name) VALUES (2,  'Almagro');
INSERT INTO neighborhoods (id, name) VALUES (3,  'Balvanera');
INSERT INTO neighborhoods (id, name) VALUES (4,  'Barracas');
INSERT INTO neighborhoods (id, name) VALUES (5,  'Belgrano');
INSERT INTO neighborhoods (id, name) VALUES (6,  'Boedo');
INSERT INTO neighborhoods (id, name) VALUES (7,  'Caballito');
INSERT INTO neighborhoods (id, name) VALUES (8,  'Chacarita');
INSERT INTO neighborhoods (id, name) VALUES (9,  'Coghlan');
INSERT INTO neighborhoods (id, name) VALUES (10, 'Colegiales');
INSERT INTO neighborhoods (id, name) VALUES (11, 'Constitución');
INSERT INTO neighborhoods (id, name) VALUES (12, 'Flores');
INSERT INTO neighborhoods (id, name) VALUES (13, 'Floresta');
INSERT INTO neighborhoods (id, name) VALUES (14, 'La Boca');
INSERT INTO neighborhoods (id, name) VALUES (15, 'La Paternal');
INSERT INTO neighborhoods (id, name) VALUES (16, 'Liniers');
INSERT INTO neighborhoods (id, name) VALUES (17, 'Mataderos');
INSERT INTO neighborhoods (id, name) VALUES (18, 'Monte Castro');
INSERT INTO neighborhoods (id, name) VALUES (19, 'Montserrat');
INSERT INTO neighborhoods (id, name) VALUES (20, 'Nueva Pompeya');
INSERT INTO neighborhoods (id, name) VALUES (21, 'Núñez');
INSERT INTO neighborhoods (id, name) VALUES (22, 'Palermo');
INSERT INTO neighborhoods (id, name) VALUES (23, 'Parque Avellaneda');
INSERT INTO neighborhoods (id, name) VALUES (24, 'Parque Chacabuco');
INSERT INTO neighborhoods (id, name) VALUES (25, 'Parque Chas');
INSERT INTO neighborhoods (id, name) VALUES (26, 'Parque Patricios');
INSERT INTO neighborhoods (id, name) VALUES (27, 'Puerto Madero');
INSERT INTO neighborhoods (id, name) VALUES (28, 'Recoleta');
INSERT INTO neighborhoods (id, name) VALUES (29, 'Retiro');
INSERT INTO neighborhoods (id, name) VALUES (30, 'Saavedra');
INSERT INTO neighborhoods (id, name) VALUES (31, 'San Cristóbal');
INSERT INTO neighborhoods (id, name) VALUES (32, 'San Nicolás');
INSERT INTO neighborhoods (id, name) VALUES (33, 'San Telmo');
INSERT INTO neighborhoods (id, name) VALUES (34, 'Vélez Sársfield');
INSERT INTO neighborhoods (id, name) VALUES (35, 'Versalles');
INSERT INTO neighborhoods (id, name) VALUES (36, 'Villa Crespo');
INSERT INTO neighborhoods (id, name) VALUES (37, 'Villa del Parque');
INSERT INTO neighborhoods (id, name) VALUES (38, 'Villa Devoto');
INSERT INTO neighborhoods (id, name) VALUES (39, 'Villa General Mitre');
INSERT INTO neighborhoods (id, name) VALUES (40, 'Villa Lugano');
INSERT INTO neighborhoods (id, name) VALUES (41, 'Villa Luro');
INSERT INTO neighborhoods (id, name) VALUES (42, 'Villa Ortúzar');
INSERT INTO neighborhoods (id, name) VALUES (43, 'Villa Pueyrredón');
INSERT INTO neighborhoods (id, name) VALUES (44, 'Villa Real');
INSERT INTO neighborhoods (id, name) VALUES (45, 'Villa Riachuelo');
INSERT INTO neighborhoods (id, name) VALUES (46, 'Villa Santa Rita');
INSERT INTO neighborhoods (id, name) VALUES (47, 'Villa Soldati');
INSERT INTO neighborhoods (id, name) VALUES (48, 'Villa Urquiza');
