# Profile: spring.profiles.active=local (Jetty/Tomcat VM options or env).
# Credenciales bd local
spring.datasource.url=jdbc:postgresql://localhost:5432/paw
spring.datasource.username=pawdbuser
spring.datasource.password=pawdbpassword

mail.app.base.url=http://localhost:8080/webapp
