# Pampero database credentials
server.port=8080
server.servlet.context-path=/api
spring.datasource.url=jdbc:postgresql://10.16.1.110:5432/paw-2026a-08
spring.datasource.username=paw-2026a-08
spring.datasource.password=1We6hhOtj

# Upload limits (bytes)
app.upload.max-image-bytes=20971520
app.upload.max-multipart-request-bytes=188743680

# User / profile validation
app.validation.registration-password-min-length=8
app.validation.profile-phone-max-length=20
app.validation.profile-phone-pattern=^[0-9+]+$

# Links in mails
mail.app.context.path=/api
